spring:
  application:
    name: attendance
  datasource:
    url: jdbc:postgresql://localhost:5432/mydatabase
    username: myuser
    password: secret
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update      # creates/updates tables automatically
    show-sql: true           # show SQL in console
    properties:
      hibernate:
        format_sql: true     # pretty print SQL
        dialect: org.hibernate.dialect.PostgreSQLDialect
